server:
  port: 8081

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Optional: JWT-related values
#jwt:
#  secret: my-secret-key
#  expiration: 86400000

