server:
  port: 8082

spring:
  application:
    name: vehicle-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# Optional: DB connection
#spring:
# datasource:
#   url: jdbc:mysql://localhost:3306/vehicle_db
#   username: root
#   password: password
